### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timchenxiaoyu** [shishir-a412ed/Docker-Migrate#2]
this migrator  can migrate docker container from one host to anthor?

**Comment by shishir-a412ed** [comment]
@timchenxiaoyu 
The usecase for this for mostly migrating containers from one backend storage to another e.g. devicemapper to overlay. You can try, it may or may not work, since the source container has a lot of host specific attributes, which might be different on the target host.

Also, This project has moved to https://github.com/projectatomic/atomic
If you want to try container migration, I would suggest you install the above tool (projectatomic/atomic) and try the `atomic storage` sub-commands.

`atomic storage` has 3 subcommands: `atomic storage export`, `atomic storage import` and `atomic storage reset`. 

Hope that helps !
Shishir

**Comment by timchenxiaoyu** [comment]
thank you your reply,I  will study projectatomic/atomic .
